--创建新闻标题表
CREATE TABLE news_tile (id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
title VARCHAR(255) COMMENT '标题',
create_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
url VARCHAR(255) COMMENT '对应的连接地址' );
